{% set name = "pytomoatt" %}
{% set version = "0.2.6" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytomoatt-{{ version }}.tar.gz
  sha256: 191b9aa605c968fe09b4b38d0d92a3441bbacfce301f1a95a203dbfc85c3f02d

build:
  entry_points:
    - pta = pytomoatt.script:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19.0,<2.0
    - pandas >=1.4.0
    - scipy
    - h5py
    - ruamel.yaml
    - xarray
    - tqdm
    - pyproj
    - scikit-learn
    - ruamel_yaml
    - urllib3

test:
  imports:
    - pytomoatt
  commands:
    - pta --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://tomoatt.com
  summary: Python API for TomoATT
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xumi1993
